version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: marketplace-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: marketplace
      MYSQL_USER: marketuser
      MYSQL_PASSWORD: market123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/sql:/docker-entrypoint-initdb.d
    networks:
      - marketplace-network

  adminer:
    image: adminer
    container_name: marketplace-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - marketplace-network

volumes:
  mysql_data:

networks:
  marketplace-network:
    driver: bridge
