// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1RSJGk1p_vaDF3v0lHNSv8GFs9xVDKOk',
    appId: '1:439834096035:web:56fdf45a05de6874486a16',
    messagingSenderId: '439834096035',
    projectId: 'marketplace-18ae4',
    authDomain: 'marketplace-18ae4.firebaseapp.com',
    storageBucket: 'marketplace-18ae4.firebasestorage.app',
    measurementId: 'G-SRL9BY3KSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPtyGyrluYwBOlQnvk00w_6vmr_mkuEAY',
    appId: '1:439834096035:android:6848600911c0cedc486a16',
    messagingSenderId: '439834096035',
    projectId: 'marketplace-18ae4',
    storageBucket: 'marketplace-18ae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYToWs1kVH-5fkbln1rVjU2NtgNgwZiaA',
    appId: '1:439834096035:ios:dad8670c7cb17cb5486a16',
    messagingSenderId: '439834096035',
    projectId: 'marketplace-18ae4',
    storageBucket: 'marketplace-18ae4.firebasestorage.app',
    iosBundleId: 'com.example.flutterMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYToWs1kVH-5fkbln1rVjU2NtgNgwZiaA',
    appId: '1:439834096035:ios:dad8670c7cb17cb5486a16',
    messagingSenderId: '439834096035',
    projectId: 'marketplace-18ae4',
    storageBucket: 'marketplace-18ae4.firebasestorage.app',
    iosBundleId: 'com.example.flutterMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1RSJGk1p_vaDF3v0lHNSv8GFs9xVDKOk',
    appId: '1:439834096035:web:374e58020d65c7f5486a16',
    messagingSenderId: '439834096035',
    projectId: 'marketplace-18ae4',
    authDomain: 'marketplace-18ae4.firebaseapp.com',
    storageBucket: 'marketplace-18ae4.firebasestorage.app',
    measurementId: 'G-KFSWC5WT59',
  );
}
